export const ACTIONS = {
  ADD_TAB: 'add-tab',
  ADD_PROFILE: 'add-profile',
  CHANGE_TAB: 'change-tab',
  CHANGE_PROFILE: 'change-profile',
  CLOSE_CONTEXT_MENU: 'close-menu',
  GET_CONTEXT_MENU: 'context-menu',
  OPEN_CONTEXT_MENU: 'open-menu',
  REMOVE_TAB: 'remove-tab',
  REQUEST_TABS: 'request-tabs',
  REQUEST_PROFILES: 'request-profiles',
  SUBSCRIBE_ACTIVE_TAB: 'subscribe-active-tab',
  SUBSCRIBE_ACTIVE_PROFILE: 'subscribe-active-profile',
  SUBSCRIBE_PROFILES: 'subscribe-profiles',
  SUBSCRIBE_TABS: 'subscribe-tabs',
  UPDATE_PROFILE: 'update-profile',
}
